### PR TITLE
Registered a new Docker image

### PR DESCRIPTION
**Pull request by yesw2000**

### CODE REVIEW

**Comment by yesw2000** [comment]
Added my first private Docker image for machine learning

**Comment by jblomer** [comment]
Please bear with us, we are currently debugging an issue with the container conversion. It should be working again soon and the we'll merge the change. Meanwhile, could you reopen the PR on CERN gitlab in the `unpacked/sync` repository? We'd prefer gitlab over the github wishlist for users who do have a CERN computing account.

**Comment by yesw2000** [comment]
Hi @jblomer ,

Following your suggestion, I reopen the PR on CERN gitlab:
[https://gitlab.cern.ch/unpacked/sync/-/merge_requests/146](https://gitlab.cern.ch/unpacked/sync/-/merge_requests/146)

Shuwei

**Comment by jblomer** [comment]
Closing, taking it from gitlab

**Pull request closed without merging**
