### PR TITLE
added ilcsoft image

### PR DESCRIPTION
**Pull request by EnginEren**
Dear all, 

I've added our custom image as Simone Mosciatti suggested (thanks!)

Cheers,
Engin

### CODE REVIEW

**Comment by siscia** [comment]
Hi there!

I have merged the PR, and hooked up the backend infrastructure.

In a while you should see it appear under /cvmfs/unpacked.cern.ch :)

**Comment by siscia** [comment]
Sorry, nope, unfortunately you will need to await a little bit more.

Singularity decide to broke in the latest release and this is broking all our integrations.

I am working on either getting rid of Singularity or hopefully they will fix the problem. We are tracking the issue here: https://github.com/sylabs/singularity/issues/4517

**Comment by siscia** [comment]
Ok, I anyway tested the integration with this new repository and the integration itself works just fine.

I add to modify your line a little bit: https://github.com/cvmfs/images-unpacked.cern.ch/commit/420861bf5ab25445cca301ee587401f33f2f42bd but now it is understood correctly from our tooling.

I will ping you back as soon as this thing with Singularity is sorted out!

**Comment by EnginEren** [comment]
Hi Simone,

thanks a lot.. No worries, I can wait. Talk to you later!

Cheers,
Engin

**Comment by siscia** [comment]
Alright, the singularity issues has been sorted out.

Your image is up in /cvmfs/unpacked.cern.ch

Let me know if you have any issue or doubt :)
Simone

**Comment by EnginEren** [comment]
Thanks a lot!  I will let you know if there is any issue :) 
Cheers

**Pull request merged**
